// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using AwesomeAssertions;
using EricksonLopez.Processes.Abstractions;
using EricksonLopez.Processes.Generator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

#pragma warning disable IL3000
namespace EricksonLopez.Processes.Generator.Tests;

[Trait("Category", "SourceGenerator")]
public class SourceGeneratorTests
{
    private static string EnsureUsings(string source)
    {
        var usings = "";
        if (!source.Contains("using System;", StringComparison.Ordinal)) usings += "using System;\n";
        if (!source.Contains("using EricksonLopez.Processes.Abstractions;", StringComparison.Ordinal)) usings += "using EricksonLopez.Processes.Abstractions;\n";
        return usings.Length > 0 ? usings + source : source;
    }

    private static (Compilation Compilation, GeneratorDriverRunResult RunResult) RunGenerator(string source, bool includeProcessesRef = true)
    {
        var syntaxTree = CSharpSyntaxTree.ParseText(EnsureUsings(source));
        var baseRefs = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic && !string.IsNullOrWhiteSpace(a.Location))
            .Select(a => (MetadataReference)MetadataReference.CreateFromFile(a.Location));

        if (includeProcessesRef)
        {
            baseRefs = baseRefs.Concat([
                MetadataReference.CreateFromFile(typeof(ProcessDefinitionAttribute).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(EricksonLopez.Processes.ProcessRegistry).Assembly.Location),
                // Include DI Abstractions so that IServiceCollection is known in the generated code.
                // Note: AddSingleton extension method requires full DI package, not available in test isolation.
                MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.IServiceCollection).Assembly.Location)
            ]);
        }

        var references = baseRefs.Distinct().ToArray();

        var compilation = CSharpCompilation.Create(
            "TestAssembly",
            [syntaxTree],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new ProcessSourceGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);

        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out var outputCompilation, out var diagnostics);

        return (outputCompilation, driver.GetRunResult());
    }

    /// <summary>
    /// Helper to get compilation errors for only the registry file (not the DI extension which requires
    /// Microsoft.Extensions.DependencyInjection full package for AddSingleton extension method).
    /// </summary>
    private static Diagnostic[] GetRegistryCompilationErrors(Compilation compilation) =>
        compilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error
                && !d.Location.GetLineSpan().Path.Contains("GeneratedProcessRegistryExtensions", StringComparison.Ordinal))
            .ToArray();

    [Fact]
    public void Generator_ShouldEmit_ExactExpectedSource_WhenProcessDefinitionPresent()
    {
        const string userSource = @"

namespace MySampleApp;

[ProcessDefinition(""order.fulfillment"", 1)]
public class SampleOrderProcess
{
}
";

        var (compilation, runResult) = RunGenerator(userSource);

        runResult.Diagnostics.Should().BeEmpty();
        // Now emits 2 files: registry metadata + DI extension
        runResult.GeneratedTrees.Should().HaveCount(2);

        var registrySource = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("GeneratedProcessRegistry.g.cs", StringComparison.Ordinal))
            .ToString()
            .Replace("\r\n", "\n", StringComparison.Ordinal)
            .Trim();

        const string expected = @"// <auto-generated/>
#nullable enable

namespace EricksonLopez.Processes.Generated;

/// <summary>
/// Generated compile-time registration metadata and helpers for discovered processes and sagas.
/// </summary>
public static class GeneratedProcessRegistry
{
    /// <summary>
    /// Populates the process registry with all discovered process definitions at compile time.
    /// </summary>
    public static void RegisterDiscoveredProcesses(global::EricksonLopez.Processes.ProcessRegistry registry)
    {
        if (registry is null) throw new global::System.ArgumentNullException(nameof(registry));

        registry.Register(
            global::EricksonLopez.Processes.Abstractions.ProcessType.From(""order.fulfillment""),
            global::EricksonLopez.Processes.Abstractions.ProcessVersion.From(1));
    }

    /// <summary>
    /// Creates and populates a new process registry with all discovered process definitions.
    /// </summary>
    public static global::EricksonLopez.Processes.ProcessRegistry CreateRegistry()
    {
        var registry = new global::EricksonLopez.Processes.ProcessRegistry();
        RegisterDiscoveredProcesses(registry);
        return registry;
    }
}";

        registrySource.Should().Be(expected.Replace("\r\n", "\n", StringComparison.Ordinal).Trim());

        // Only check registry file errors; DI extension requires full DI package at runtime.
        GetRegistryCompilationErrors(compilation).Should().BeEmpty();
    }

    [Fact]
    public void Generator_ShouldEmit_DiExtensionFile_WhenProcessDefinitionPresent()
    {
        const string userSource = @"

namespace MySampleApp;

[ProcessDefinition(""order.fulfillment"", 1)]
public class SampleOrderProcess
{
}
";

        var (compilation, runResult) = RunGenerator(userSource);

        runResult.Diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(2);

        var diExtSource = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("GeneratedProcessRegistryExtensions.g.cs", StringComparison.Ordinal))
            .ToString()
            .Replace("\r\n", "\n", StringComparison.Ordinal)
            .Trim();

        const string expected = @"// <auto-generated/>
#nullable enable

namespace EricksonLopez.Processes.Generated;

/// <summary>
/// Generated compile-time dependency injection extension methods for EricksonLopez.Processes.
/// Provides zero-reflection, AOT-safe registration of all discovered process definitions.
/// </summary>
public static class GeneratedProcessRegistryExtensions
{
    /// <summary>
    /// Registers all compile-time discovered process and saga definitions into the process registry.
    /// Call this during application startup to populate <see cref=""global::EricksonLopez.Processes.IProcessRegistry""/> without runtime reflection.
    /// </summary>
    /// <remarks>
    /// This method was generated at compile time and registers 1 process definition(s):
    /// <br/>• <c>order.fulfillment</c> (v1)
    /// </remarks>
    /// <param name=""services"">The <see cref=""global::Microsoft.Extensions.DependencyInjection.IServiceCollection""/> to configure.</param>
    /// <returns>The same <see cref=""global::Microsoft.Extensions.DependencyInjection.IServiceCollection""/> for chaining.</returns>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedProcesses(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        global::System.ArgumentNullException.ThrowIfNull(services);

        services.AddSingleton<global::EricksonLopez.Processes.ProcessRegistry>(static _ =>
        {
            var registry = new global::EricksonLopez.Processes.ProcessRegistry();
            GeneratedProcessRegistry.RegisterDiscoveredProcesses(registry);
            return registry;
        });

        services.AddSingleton<global::EricksonLopez.Processes.IProcessRegistry>(
            static sp => sp.GetRequiredService<global::EricksonLopez.Processes.ProcessRegistry>());

        return services;
    }
}";

        diExtSource.Should().Be(expected.Replace("\r\n", "\n", StringComparison.Ordinal).Trim());
    }

    [Fact]
    public void Generator_ShouldRecognizeAllFourAttributeSyntaxForms()
    {
        const string userSource = @"

namespace MySampleApp;

[ProcessDefinition(""p.short"", 1)]
public class ProcessShort { }

[ProcessDefinitionAttribute(""p.long"", 2)]
public class ProcessLong { }

[SagaDefinition(""s.short"", 3)]
public class SagaShort { }

[SagaDefinitionAttribute(""s.long"", 4)]
public class SagaLong { }
";

        var (compilation, runResult) = RunGenerator(userSource);

        runResult.Diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(2);

        var registrySource = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("GeneratedProcessRegistry.g.cs", StringComparison.Ordinal))
            .ToString();

        registrySource.Should().Contain("\"p.short\"");
        registrySource.Should().Contain("ProcessVersion.From(1)");
        registrySource.Should().Contain("\"p.long\"");
        registrySource.Should().Contain("ProcessVersion.From(2)");
        registrySource.Should().Contain("\"s.short\"");
        registrySource.Should().Contain("ProcessVersion.From(3)");
        registrySource.Should().Contain("\"s.long\"");
        registrySource.Should().Contain("ProcessVersion.From(4)");
    }

    [Fact]
    public void Generator_ShouldHandleSingleArgumentAttributeWithoutVersion_LengthCheckBoundary()
    {
        const string userSource = @"
namespace MySampleApp;

public class ProcessDefinitionAttribute : System.Attribute
{
    public ProcessDefinitionAttribute(string type) {}
}

[ProcessDefinition(""single.exact.arg"")]
public class ExactOneArgProcess { }
";

        var (compilation, runResult) = RunGenerator(userSource, includeProcessesRef: false);

        runResult.Diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(2);

        var registrySource = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("GeneratedProcessRegistry.g.cs", StringComparison.Ordinal))
            .ToString();

        registrySource.Should().Contain("\"single.exact.arg\"");
        registrySource.Should().Contain("ProcessVersion.From(1)");
    }

    [Fact]
    public void Generator_ShouldFallbackToClassName_WhenProcessTypeIsWhitespace()
    {
        const string userSource = @"

namespace MySampleApp;

[ProcessDefinition(""   "", 2)]
public class WhitespaceNamedProcess { }
";

        var (compilation, runResult) = RunGenerator(userSource);

        runResult.Diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(2);

        var registrySource = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("GeneratedProcessRegistry.g.cs", StringComparison.Ordinal))
            .ToString();

        registrySource.Should().Contain("\"WhitespaceNamedProcess\"");
        registrySource.Should().Contain("ProcessVersion.From(2)");
    }

    [Fact]
    public void Generator_ShouldProduceNoSource_WhenNoProcessAttributesPresent()
    {
        const string userSource = @"
namespace MySampleApp;

public class PlainServiceWithoutAttributes
{
    public void DoWork() {}
}

[System.Obsolete]
public class ObsoleteService
{
}
";

        var (compilation, runResult) = RunGenerator(userSource);

        runResult.Diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().BeEmpty();
    }

    [Fact]
    public void Generator_ShouldHandleGlobalNamespaceClasses()
    {
        const string userSource = @"

[ProcessDefinition(""global.proc"", 1)]
public class GlobalProcess
{
}
";

        var (compilation, runResult) = RunGenerator(userSource);

        runResult.Diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(2);

        var registrySource = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("GeneratedProcessRegistry.g.cs", StringComparison.Ordinal))
            .ToString();

        registrySource.Should().Contain("\"global.proc\"");
    }

    [Fact]
    public void Generator_ShouldFallbackToClassName_WhenAttributeHasNoArguments()
    {
        const string userSource = @"
namespace MySampleApp;

public class ProcessDefinitionAttribute : System.Attribute {}

[ProcessDefinition]
public class DefaultNamedProcess
{
}
";

        var (compilation, runResult) = RunGenerator(userSource, includeProcessesRef: false);

        runResult.GeneratedTrees.Should().HaveCount(2);

        var registrySource = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("GeneratedProcessRegistry.g.cs", StringComparison.Ordinal))
            .ToString();

        registrySource.Should().Contain("\"DefaultNamedProcess\"");
        registrySource.Should().Contain("ProcessVersion.From(1)");
    }

    [Fact]
    public void Generator_ShouldHandleNestedClasses_WithProcessAndSagaDefinitions()
    {
        const string userSource = @"

namespace MySampleApp;

public static class OuterContainer
{
    [ProcessDefinition(""nested.order"", 1)]
    public class NestedOrderProcess
    {
    }

    [SagaDefinition(""nested.saga"", 2)]
    public class NestedSagaProcess
    {
    }

    [ProcessDefinition(""nested.default"")]
    public class NestedDefaultVersionProcess
    {
    }
}
";

        var (compilation, runResult) = RunGenerator(userSource);

        runResult.Diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(2);

        var registrySource = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("GeneratedProcessRegistry.g.cs", StringComparison.Ordinal))
            .ToString();

        registrySource.Should().Contain("\"nested.order\"");
        registrySource.Should().Contain("ProcessVersion.From(1)");
        registrySource.Should().Contain("\"nested.saga\"");
        registrySource.Should().Contain("ProcessVersion.From(2)");
        registrySource.Should().Contain("\"nested.default\"");

        // Only check registry file errors; DI extension requires full DI package at runtime.
        GetRegistryCompilationErrors(compilation).Should().BeEmpty();
    }

    [Fact]
    public void Generator_ShouldEmit_CreateRegistryHelper_ThatCompilesSuccessfully()
    {
        const string userSource = @"
namespace MySampleApp;

[ProcessDefinition(""invoice.flow"", 2)]
public class InvoiceProcess { }
";

        var (compilation, runResult) = RunGenerator(userSource);

        runResult.Diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(2);

        var registrySource = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("GeneratedProcessRegistry.g.cs", StringComparison.Ordinal))
            .ToString();

        registrySource.Should().Contain("CreateRegistry()");
        registrySource.Should().Contain("RegisterDiscoveredProcesses(registry)");

        // Only check registry file errors; DI extension requires full DI package at runtime.
        GetRegistryCompilationErrors(compilation).Should().BeEmpty();
    }

    [Fact]
    public void Generator_DiExtension_ShouldContain_AllDiscoveredProcessDefinitions_InXmlComments()
    {
        const string userSource = @"
namespace MySampleApp;

[ProcessDefinition(""payment.process"", 1)]
public class PaymentProcess { }

[SagaDefinition(""order.saga"", 2)]
public class OrderSaga { }
";

        var (compilation, runResult) = RunGenerator(userSource);

        runResult.Diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(2);

        var diSource = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("GeneratedProcessRegistryExtensions.g.cs", StringComparison.Ordinal))
            .ToString()
            .Replace("\r\n", "\n", StringComparison.Ordinal)
            .Trim();

        const string expected = @"// <auto-generated/>
#nullable enable

namespace EricksonLopez.Processes.Generated;

/// <summary>
/// Generated compile-time dependency injection extension methods for EricksonLopez.Processes.
/// Provides zero-reflection, AOT-safe registration of all discovered process definitions.
/// </summary>
public static class GeneratedProcessRegistryExtensions
{
    /// <summary>
    /// Registers all compile-time discovered process and saga definitions into the process registry.
    /// Call this during application startup to populate <see cref=""global::EricksonLopez.Processes.IProcessRegistry""/> without runtime reflection.
    /// </summary>
    /// <remarks>
    /// This method was generated at compile time and registers 2 process definition(s):
    /// <br/>• <c>payment.process</c> (v1)
    /// <br/>• <c>order.saga</c> (v2)
    /// </remarks>
    /// <param name=""services"">The <see cref=""global::Microsoft.Extensions.DependencyInjection.IServiceCollection""/> to configure.</param>
    /// <returns>The same <see cref=""global::Microsoft.Extensions.DependencyInjection.IServiceCollection""/> for chaining.</returns>
    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedProcesses(
        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        global::System.ArgumentNullException.ThrowIfNull(services);

        services.AddSingleton<global::EricksonLopez.Processes.ProcessRegistry>(static _ =>
        {
            var registry = new global::EricksonLopez.Processes.ProcessRegistry();
            GeneratedProcessRegistry.RegisterDiscoveredProcesses(registry);
            return registry;
        });

        services.AddSingleton<global::EricksonLopez.Processes.IProcessRegistry>(
            static sp => sp.GetRequiredService<global::EricksonLopez.Processes.ProcessRegistry>());

        return services;
    }
}";

        diSource.Should().Be(expected.Replace("\r\n", "\n", StringComparison.Ordinal).Trim());
    }

    [Fact]
    public void Generator_ShouldFallbackToClassName_WhenFirstArgumentIsNotString()
    {
        const string userSource = @"
namespace MySampleApp;

public class ProcessDefinitionAttribute : System.Attribute
{
    public ProcessDefinitionAttribute(int id) {}
}

[ProcessDefinition(42)]
public class NonStringArgProcess { }
";

        var (compilation, runResult) = RunGenerator(userSource, includeProcessesRef: false);

        runResult.Diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(2);

        var registrySource = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("GeneratedProcessRegistry.g.cs", StringComparison.Ordinal))
            .ToString();

        registrySource.Should().Contain("\"NonStringArgProcess\"");
        registrySource.Should().Contain("ProcessVersion.From(1)");
    }

    [Fact]
    public void Generator_ShouldFallbackToDefaultVersion_WhenSecondArgumentIsNotInt()
    {
        const string userSource = @"
namespace MySampleApp;

public class ProcessDefinitionAttribute : System.Attribute
{
    public ProcessDefinitionAttribute(string type, string note) {}
}

[ProcessDefinition(""custom.type"", ""note"")]
public class NonIntVersionArgProcess { }
";

        var (compilation, runResult) = RunGenerator(userSource, includeProcessesRef: false);

        runResult.Diagnostics.Should().BeEmpty();
        runResult.GeneratedTrees.Should().HaveCount(2);

        var registrySource = runResult.GeneratedTrees
            .Single(t => t.FilePath.EndsWith("GeneratedProcessRegistry.g.cs", StringComparison.Ordinal))
            .ToString();

        registrySource.Should().Contain("\"custom.type\"");
        registrySource.Should().Contain("ProcessVersion.From(1)");
    }

    [Fact]
    public void Generator_ShouldIgnoreClassesWithUnresolvedAttributes()
    {
        const string userSource = @"
namespace MySampleApp;

[SomeUnresolvedAttribute]
public class UnresolvedAttrProcess { }
";

        var (compilation, runResult) = RunGenerator(userSource, includeProcessesRef: false);

        runResult.GeneratedTrees.Should().BeEmpty();
    }
}
#pragma warning restore IL3000




