<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Processes\EricksonLopez.Processes.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.SystemTextJson\EricksonLopez.Processes.SystemTextJson.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>
</Project>
