<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.Abstractions\EricksonLopez.Processes.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes\EricksonLopez.Processes.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.DependencyInjection\EricksonLopez.Processes.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.SystemTextJson\EricksonLopez.Processes.SystemTextJson.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.Testing\EricksonLopez.Processes.Testing.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.Outbox\EricksonLopez.Processes.Outbox.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.Mediator\EricksonLopez.Processes.Mediator.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.Events\EricksonLopez.Processes.Events.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.Storage.PostgreSql\EricksonLopez.Processes.Storage.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.Storage.SqlServer\EricksonLopez.Processes.Storage.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.Storage.Sqlite\EricksonLopez.Processes.Storage.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.Storage.MySql\EricksonLopez.Processes.Storage.MySql.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.Storage.MariaDb\EricksonLopez.Processes.Storage.MariaDb.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.Storage.Oracle\EricksonLopez.Processes.Storage.Oracle.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Processes.Generator\EricksonLopez.Processes.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
  </ItemGroup>
</Project>
