// Copyright © Erickson Lopez. MIT License.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EricksonLopez.Processes.Generator;

/// <summary>
/// Generates compile-time static registration and metadata tables for discovered Process and Saga definitions.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ProcessSourceGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cds && cds.AttributeLists.Any(),
                transform: static (genContext, _) => ExtractProcessInfo(genContext))
            .Where(static info => info is not null);

        var collected = classDeclarations.Collect();

        context.RegisterSourceOutput(collected, static (spc, processes) =>
        {
            if (processes.IsEmpty)
            {
                return;
            }

            GenerateRegistrationMetadata(spc, processes!);
            GenerateDependencyInjectionExtension(spc, processes!);
        });
    }

    private static ProcessModel? ExtractProcessInfo(GeneratorSyntaxContext context)
    {
        var classSyntax = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classSyntax) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }

        var attributeData = classSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass is { Name: "ProcessDefinitionAttribute" } or { Name: "SagaDefinitionAttribute" });

        if (attributeData is null)
        {
            return null;
        }

        return CreateModelFromAttribute(classSymbol.Name, attributeData);
    }

    private static ProcessModel CreateModelFromAttribute(string defaultName, AttributeData attributeData)
    {
        string processType = defaultName;
        int version = 1;

        if (attributeData.ConstructorArguments.Length > 0 && attributeData.ConstructorArguments[0].Value is string pt && !string.IsNullOrWhiteSpace(pt))
        {
            processType = pt;
        }

        if (attributeData.ConstructorArguments.Length > 1 && attributeData.ConstructorArguments[1].Value is int v)
        {
            version = v;
        }

        return new ProcessModel(ProcessType: processType, Version: version);
    }

    private static void GenerateRegistrationMetadata(SourceProductionContext context, ImmutableArray<ProcessModel> processes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace EricksonLopez.Processes.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated compile-time registration metadata and helpers for discovered processes and sagas.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedProcessRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Populates the process registry with all discovered process definitions at compile time.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static void RegisterDiscoveredProcesses(global::EricksonLopez.Processes.ProcessRegistry registry)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (registry is null) throw new global::System.ArgumentNullException(nameof(registry));");
        sb.AppendLine();

        foreach (var proc in processes)
        {
            sb.AppendLine($"        registry.Register(");
            sb.AppendLine($"            global::EricksonLopez.Processes.Abstractions.ProcessType.From(\"{proc.ProcessType}\"),");
            sb.AppendLine($"            global::EricksonLopez.Processes.Abstractions.ProcessVersion.From({proc.Version}));");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Creates and populates a new process registry with all discovered process definitions.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static global::EricksonLopez.Processes.ProcessRegistry CreateRegistry()");
        sb.AppendLine("    {");
        sb.AppendLine("        var registry = new global::EricksonLopez.Processes.ProcessRegistry();");
        sb.AppendLine("        RegisterDiscoveredProcesses(registry);");
        sb.AppendLine("        return registry;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedProcessRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void GenerateDependencyInjectionExtension(SourceProductionContext context, ImmutableArray<ProcessModel> processes)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace EricksonLopez.Processes.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated compile-time dependency injection extension methods for EricksonLopez.Processes.");
        sb.AppendLine("/// Provides zero-reflection, AOT-safe registration of all discovered process definitions.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedProcessRegistryExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all compile-time discovered process and saga definitions into the process registry.");
        sb.AppendLine("    /// Call this during application startup to populate <see cref=\"global::EricksonLopez.Processes.IProcessRegistry\"/> without runtime reflection.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <remarks>");
        sb.AppendLine($"    /// This method was generated at compile time and registers {processes.Length} process definition(s):");
        foreach (var proc in processes)
        {
            sb.AppendLine($"    /// <br/>• <c>{proc.ProcessType}</c> (v{proc.Version})");
        }
        sb.AppendLine("    /// </remarks>");
        sb.AppendLine("    /// <param name=\"services\">The <see cref=\"global::Microsoft.Extensions.DependencyInjection.IServiceCollection\"/> to configure.</param>");
        sb.AppendLine("    /// <returns>The same <see cref=\"global::Microsoft.Extensions.DependencyInjection.IServiceCollection\"/> for chaining.</returns>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedProcesses(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        global::System.ArgumentNullException.ThrowIfNull(services);");
        sb.AppendLine();
        sb.AppendLine("        services.AddSingleton<global::EricksonLopez.Processes.ProcessRegistry>(static _ =>");
        sb.AppendLine("        {");
        sb.AppendLine("            var registry = new global::EricksonLopez.Processes.ProcessRegistry();");
        sb.AppendLine("            GeneratedProcessRegistry.RegisterDiscoveredProcesses(registry);");
        sb.AppendLine("            return registry;");
        sb.AppendLine("        });");
        sb.AppendLine();
        sb.AppendLine("        services.AddSingleton<global::EricksonLopez.Processes.IProcessRegistry>(");
        sb.AppendLine("            static sp => sp.GetRequiredService<global::EricksonLopez.Processes.ProcessRegistry>());");
        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedProcessRegistryExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed record ProcessModel(
        string ProcessType,
        int Version);
}




